defaults: &defaults
help_page_url: "http://www.railstutorial.org/help"
book_url: "http://www.railstutorial.org/book"
google_logo_url: "https://img.icons8.com/color/48/000000/google-logo.png"
lucide_js_path: "https://cdn.jsdelivr.net/npm/lucide@latest/dist/umd/lucide.js"

page_6: 6

user:
  max_name_length: 50
  max_email_length: 255
  hundred_years: 100

word:
  pagy_items: 10
  filter_days:
    last_7_days: 7
    last_30_days: 30
  date_format: "%d/%m/%Y"

course:
  min_duration: 1
  max_duration: 365
  date_format: "%d/%m/%Y"

question:
  answer_defaults_number: 4
  question_types:
    single_choice: "single_choice"
    multiple_choice: "multiple_choice"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
