defaults: &defaults
help_page_url: "http://www.railstutorial.org/help"
book_url: "http://www.railstutorial.org/book"
google_logo_url: "https://img.icons8.com/color/48/000000/google-logo.png"
lucide_js_path: "https://cdn.jsdelivr.net/npm/lucide@latest/dist/umd/lucide.js"

user:
  max_name_length: 50
  max_email_length: 255
  hundred_years: 100

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
